// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJUY7-kt1dBgn5FjeES1o_Bc_G-8AU6o',
    appId: '1:177566461480:web:40aba44c3912a70bd74f1d',
    messagingSenderId: '177566461480',
    projectId: 'esp8266-2dca6',
    authDomain: 'esp8266-2dca6.firebaseapp.com',
    databaseURL: 'https://esp8266-2dca6-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-2dca6.appspot.com',
    measurementId: 'G-B92NSJVMTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCY87NkoweFnPvyNiExXS5ssgvkaU2j1w',
    appId: '1:177566461480:android:771c546212ddbc64d74f1d',
    messagingSenderId: '177566461480',
    projectId: 'esp8266-2dca6',
    databaseURL: 'https://esp8266-2dca6-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-2dca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9cY0LHvfKx4vZAzjmk5eJyKQ_3eSOH0c',
    appId: '1:177566461480:ios:be76e27d285530b1d74f1d',
    messagingSenderId: '177566461480',
    projectId: 'esp8266-2dca6',
    databaseURL: 'https://esp8266-2dca6-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-2dca6.appspot.com',
    iosBundleId: 'com.example.appLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9cY0LHvfKx4vZAzjmk5eJyKQ_3eSOH0c',
    appId: '1:177566461480:ios:dba74ffa457880d8d74f1d',
    messagingSenderId: '177566461480',
    projectId: 'esp8266-2dca6',
    databaseURL: 'https://esp8266-2dca6-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-2dca6.appspot.com',
    iosBundleId: 'com.example.appLocation.RunnerTests',
  );
}
